services:
  frontend:
    build:
      context: frontend
    container_name: hng_fe
    image: trojancodes/hng9_fe
    ports:
      - "3000:3000"
  api:
    build:
      context: api
    container_name: hng_be
    image: trojancodes/hng9_be
    ports:
      - "8000:8000"