name: Deployment Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - "main"
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hng9_fe:latest
      - name: Build and push the Backend
        uses: docker/build-push-action@v3
        with:
          context: api
          file: api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hng9_be:latest
